### ISSUE TITLE
Collection specific metadata templates

### ISSUE THREAD

**Issue by bmrgoldman** [psu-libraries/cho#16]
As a metadata specialist, I would like collection specific metadata templates so that I can apply metadata requirements that build off the baseline repository template.

Additional user story from Linda B.
As a metadata manager, I need to be able to make a general metadata template, so metadata creators have a consistent set of metadata fields to start a new project.

**Comment by ntallman** [comment]
Related: #105, #84, #161

**Comment by cam156** [comment]
Allow the metadata to be different for the collection.  At the collection level select all options that could be contained.  Documents in the collection may or may not include the same metadata for Images.

Build your own template process for each collection.  Could be 1000s different collections each with different metadata templates.  What does the input for look like for this collection.

**Comment by cam156** [comment]
From the slack conversation:

I think we're mixing up two separate things: collection-level administrative metadata for backoffice needs (not public) and collection-specific metadata templates that can be used for adding new works to a collection, a collection that may have unique metadata needs.
Since we are planning to have templates for different work-types (formats), these collection-level templates will have to inherit those requirements.
So, when I'm creating a collection, I get presented with a question and checkboxes: This collection will contain () photographs () videos ()documents () audio, etc. etc.
This will make certain fields required to be in the collection-level template, because the video works will need field X.
The choices of format will put limits around the a la carte metadata field options.

**Comment by cam156** [comment]
to complete this epic we need to close:
 1. Collection Level Object for storing Collection Configuration #247
 1. Create wireframes:
    1. Create a Metadata Field Definition Template Wireframe #248
    1. Create Collection Creation/ Edit Wireframe #249

    **note:** no index view is needed because access will be through the collection edit page
 1. Implement Collection Creation/ Edit Wireframe #250
 1. Implement a Metadata Field Definition Template Wireframe #251
 1. Apply template to edit form for work in a collection #252
 1. Apply template to view page for work in a collection #253

**Comment by awead** [comment]
Closed, replaced with #320
