### ISSUE TITLE
Should change set persisters always return the change set?

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#298]
In our controllers, the change set persister tends to return the change set, with `errors` populated when there is a problem, and the newly created or updated resource if it is persisted correctly. This is a bit confusing because depending on the case, you might have a valkyrie resource or a change set.

**Comment by cam156** [comment]
This would need to be a change at the Valkyrie level since changing it breaks the shared spec for ChangeSet Persister.  This line is really not correct though since the routine either responds with a change_set of an object (https://github.com/psu-libraries/cho/blob/master/app/cho/data_dictionary/fields_controller.rb#L47)

We could look at hiding the complexity in persist_changes

**Comment by awead** [comment]
@cam156 maybe we should make this a ticket in Valkyrie.

**Comment by awead** [comment]
No, they shouldn't because that's not what Valkyrie does.
