### ISSUE TITLE
Improve Solr Indexing of Dates

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#726]
There are two solr fields for each date field in the metadata schema. A text-based Valkyrie field and a date-based Solr field. The Valkyrie field should be used for display purposes only and not indexed. The Solr field should be hidden from display and indexed.

Enhancement to #267

**Comment by awead** [comment]
TODO:
* explore solutions for indexing EDTF dates in Solr so that they are actual dates and can be queried as such

Possible Solutions:
* two fields for each "date", start and end
* additional human-readable date

Ex:
2010-05 becomes "May 2010", start date 2010-05-01-00:00:00T (solr date), end date 2010-05-31-23:59:59T

**Comment by awead** [comment]
1. Expand unambiguous dates into their ranges
    * determine which solr field to use, such as a date range
2. Ambiguous dates, such as "1984?" and expand it out into a range with a configured +/- tolerance value
    * tolerance values can be configured per unit, such as +/- 1 year, +/- 10 days

**Comment by rschenk** [comment]
Hard problems such as how to handle intervals and sets, we are going to punt for now

**Comment by awead** [comment]
Solr's date rang field https://lucene.apache.org/solr/guide/6_6/working-with-dates.html seems to support ranges expressed as edtf. For example:

> 2000-11 – The entire month of November, 2000.
